#!/usr/bin/env python

import requests

# TODO: If you have your own Client ID and secret, put down their values here:
clientId = "FREE_TRIAL_ACCOUNT"
clientSecret = "PUBLIC_SECRET"

# TODO: Specify your translation requirements here:
fromLang = "en"
toLang = "pt"
text = "Let's have some fun!"

jsonBody = {
    'fromLang': fromLang,
    'toLang': toLang,
    'text': text
}

headers = {
    'X-WM-CLIENT-ID': clientId, 
    'X-WM-CLIENT-SECRET': clientSecret
}

r = requests.post('http://api.whatsmate.net/v1/translation/translate', 
    headers=headers,
    json=jsonBody)

print("Status code: " + str(r.status_code))
print("Translated Text: " + str(r.content))
